### ISSUE TITLE
Launching server "kotlin" failed

### ISSUE THREAD

**Issue by wexder** [weirongxu/coc-kotlin#4]
### Result from CocInfo
![image](https://user-images.githubusercontent.com/24979302/124356987-821a8000-dc19-11eb-8480-34266cf3a3c0.png)

### Description
Launching server "kotlin" failed

### Extension version
0.0.6

### Additional context
If I config the language server by using coc langaugeserver config like
```
"languageserver": {
    "kotlin": {
      "command": "/home/wexder/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server",
      "filetypes": ["kotlin"]
    }
  }
```
it works.

**Comment by shitpostbotmin** [comment]
facing the same issue

output from CocInfo
```
## versions

vim version: NVIM v0.4.4
node version: v14.8.0
coc.nvim version: 0.0.80-131f6b267f
coc.nvim directory: /Users/rhys/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-07-04T20:16:57.567 INFO (pid:19683) [plugin] - coc.nvim 0.0.80-131f6b267f initialized with node: v14.8.0 after 38ms
2021-07-04T20:17:11.523 ERROR (pid:19683) [language-client-index] - Error: spawn /Users/rhys/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/rhys/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server',
  path: '/Users/rhys/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server',
  spawnargs: []
}
2021-07-04T20:17:11.601 INFO (pid:19683) [coc-java] - Using java from /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home, version: 11
2021-07-04T20:17:11.634 INFO (pid:19683) [extension:coc-java] - Starting Java server with: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /Users/rhys/.config/coc/extensions/coc-java-data/server/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar -configuration /Users/rhys/.config/coc/extensions/coc-java-data/server/config_mac -data /Users/rhys/.config/coc/extensions/coc-java-data/jdt_ws_49709791ffbe0420a0f73f67cce5e84a
2021-07-04T20:17:11.634 INFO (pid:19683) [coc-java] - JDT Language Server starting at /Users/rhys/repos/dharmod
2021-07-04T20:17:11.634 INFO (pid:19683) [services] - registered service "java"
2021-07-04T20:17:11.637 INFO (pid:19683) [language-client-index] - Language server "java" started with 19692
2021-07-04T20:19:40.053 INFO (pid:19683) [attach] - receive notification: showInfo []
```

**Comment by weirongxu** [comment]
Seems to be conflict with the coc-java option, I'll check this later

**Comment by arynxd** [comment]
Similar issue, however i dont have the Java server installed
CocInfo:

```
  1 undefined## versions                                                                                                                                                                    
  2                                                                                                                                                                                         
  3 vim version: NVIM v0.4.4                                                                                                                                                                
  4 node version: v16.0.0                                                                                                                                                                   
  5 coc.nvim version: 0.0.80-131f6b267f                                                                                                                                                     
  6 coc.nvim directory: /home/aryn/.local/share/nvim/plugged/coc.nvim                                                                                                                       
  7 term: xterm-kitty                                                                                                                                                                       
  8 platform: linux                                                                                                                                                                         
  9                                                                                                                                                                                         
 10 ## Log of coc.nvim                                                                                                                                                                      
 11                                                                                                                                                                                         
 12 2021-07-07T17:51:29.659 INFO (pid:24953) [services] - registered service "languageserver.kotlin"                                                                                        
 13 2021-07-07T17:51:29.662 INFO (pid:24953) [plugin] - coc.nvim 0.0.80-131f6b267f initialized with node: v16.0.0 after 58ms                                                                
 14 2021-07-07T17:51:32.257 INFO (pid:24953) [services] - kotlin state change: stopped => starting                                                                                          
 15 2021-07-07T17:51:32.272 INFO (pid:24953) [language-client-index] - Language server "languageserver.kotlin" started with 25000                                                           
 16 2021-07-07T17:51:32.608 ERROR (pid:24953) [language-client-index] - Error: spawn /home/aryn/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server E
NOENT                                                                                                                                                                                       
 17     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)                                                                                                         
 18     at onErrorNT (node:internal/child_process:480:16)                                                                                                                                   
 19     at processTicksAndRejections (node:internal/process/task_queues:83:21) {                                                                                                            
 20   errno: -2,                                                                                                                                                                            
 21   code: 'ENOENT',                                                                                                                                                                       
 22   syscall: 'spawn /home/aryn/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server',                                                               
 23   path: '/home/aryn/.config/coc/extensions/coc-kotlin-data/langServerInstall/server/bin/kotlin-language-server',                                                                        
 24   spawnargs: []                                                                                                                                                                         
 25 }                                                                                                                                                                                       
 26 2021-07-07T17:51:37.322 INFO (pid:24953) [attach] - receive notification: showInfo []                                                                                                   
 27 2021-07-07T17:51:41.883 INFO (pid:24953) [services] - kotlin state change: starting => running                                                                                          
 28 2021-07-07T17:51:41.888 INFO (pid:24953) [services] - service languageserver.kotlin started                                                                                             
 29 2021-07-07T17:53:16.603 INFO (pid:24953) [attach] - receive notification: showInfo []
```
